name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        test_name:
          - CommandBuilderTests
          - NetworkTests
          - ServerManagerTests
          - WindowManagerTests
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run test
      run: make test-${{ matrix.test_name }}
